spring:

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    topic: __keyevent@0__:expired

  task:
    pool:
      corePoolSize: 5
      maxPoolSize: 10
      keepAliveSeconds: 60
      queueCapacity: 100
      threadNamePrefix: ytoThreadPool